### ISSUE TITLE
Enhance Adding users to Threads

### ISSUE THREAD

**Issue by Malix-Labs** [scratch-for-discord/Discord_Community_Bot#5]
With [this block](https://discord.com/channels/932651844344373278/932651845447483428/990896847579123762)

[![block](https://media.discordapp.net/attachments/932651845447483428/990896847075835914/unknown.png)](https://discord.com/channels/932651844344373278/932651845447483428/990896847579123762)

[reference](https://discord.com/channels/932651844344373278/932651845447483428/990896847579123762)

**Comment by noxyyk** [comment]
Forum channels
